name: Deploy Website - Production

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.PROD_AWS_REGION }}

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./content/ "s3://${{ secrets.PROD_AWS_S3_BUCKET }}/www.getneteurope.com/" --delete

    - name: Invalidate Cloudfront Cache
      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.PROD_AWS_CF_DIST_ID }} --paths "/*"
